import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";

import type { ActivationCodeDraft } from "@/data/contracts";
import { getRepository } from "@/data/repository";
import { PLAN_IDS, PLANS, isPlanId } from "@/domain/billing/plans";

type Plan = ActivationCodeDraft["plan"];

/** A <select> can carry anything, so the plan is checked against the catalogue. */
function planFrom(value: string): Plan {
  return isPlanId(value) ? value : "core";
}

/**
 * Staff-only code creation.
 *
 * The code itself is generated by the database (create_activation_code), never
 * typed here, and the row is written with status 'pending'. Nothing about this
 * form opens a workspace: the customer has to enter the code themselves, from
 * the email named here.
 */
export function ActivationCodeForm({ onDone }: { onDone?: () => void }) {
  const repo = getRepository();
  const queryClient = useQueryClient();
  const [notice, setNotice] = useState<string | null>(null);

  const mutation = useMutation({
    mutationFn: (draft: ActivationCodeDraft) => repo.createActivationCode(draft),
    onSuccess: (code) => {
      void queryClient.invalidateQueries({ queryKey: ["activation-codes"] });
      setNotice(
        `Code ${code.code} created for ${code.email}. It only works entered by that address, once.`,
      );
    },
  });

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const renewsOn = String(form.get("renews-on") ?? "").trim();
    mutation.mutate({
      companyName: String(form.get("company-name") ?? "").trim(),
      email: String(form.get("email") ?? "").trim(),
      plan: planFrom(String(form.get("plan") ?? "core")),
      renewsOn: renewsOn || null,
      note: String(form.get("note") ?? "").trim() || null,
    });
  };

  const inputClass =
    "focusable mt-1 w-full rounded-sm border border-input bg-background px-3 py-2 text-sm";

  return (
    <form
      onSubmit={handleSubmit}
      aria-labelledby="activation-code-form-heading"
      className="rounded-md border border-border bg-card p-4"
    >
      <h2 id="activation-code-form-heading" className="text-sm font-semibold text-foreground">
        Create activation code
      </h2>
      <p className="mt-1 text-xs text-muted-foreground">
        The company starts as a demo workspace the moment the customer signs up; this code is what
        turns it into their real one.
      </p>

      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <div>
          <label htmlFor="company-name" className="block text-sm font-medium">
            Company name
          </label>
          <input
            id="company-name"
            name="company-name"
            required
            maxLength={200}
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="email" className="block text-sm font-medium">
            Customer email
          </label>
          <input
            id="email"
            name="email"
            type="email"
            required
            className={inputClass}
            aria-describedby="email-hint"
          />
          <p id="email-hint" className="mt-1 text-xs text-muted-foreground">
            The code is locked to this address; it does nothing for anyone else.
          </p>
        </div>
        <div>
          <label htmlFor="plan" className="block text-sm font-medium">
            Plan
          </label>
          <select id="plan" name="plan" defaultValue="core" className={inputClass}>
            {PLAN_IDS.map((planId) => (
              <option key={planId} value={planId}>
                {PLANS[planId].label}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label htmlFor="renews-on" className="block text-sm font-medium">
            Subscription renews on
          </label>
          <input id="renews-on" name="renews-on" type="date" className={inputClass} />
          <p className="mt-1 text-xs text-muted-foreground">
            Optional. Shown on the dashboard once the workspace is live.
          </p>
        </div>
        <div className="sm:col-span-2">
          <label htmlFor="note" className="block text-sm font-medium">
            Internal note
          </label>
          <input
            id="note"
            name="note"
            maxLength={500}
            placeholder="Deal reference, who promised it, when to follow up"
            className={inputClass}
          />
        </div>
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        <button
          type="submit"
          disabled={mutation.isPending}
          className="focusable rounded-sm bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60"
        >
          {mutation.isPending ? "Creating…" : "Create code"}
        </button>
        {onDone ? (
          <button
            type="button"
            onClick={onDone}
            className="focusable rounded-sm border border-border px-3 py-2 text-sm font-medium"
          >
            Cancel
          </button>
        ) : null}
      </div>

      {notice ? (
        <p
          role="status"
          className="mt-3 rounded-sm border border-border bg-muted px-3 py-2 text-xs"
        >
          {notice}
        </p>
      ) : null}
      {mutation.isError ? (
        <p
          role="alert"
          className="mt-3 rounded-sm border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs font-semibold text-destructive"
        >
          {mutation.error instanceof Error
            ? mutation.error.message
            : "Could not create the activation code."}
        </p>
      ) : null}
    </form>
  );
}
