/**
 * Task 12 - the single source of truth for "every table this app keeps
 * customer data in, scoped by company_id" - shared by export-company.ts and
 * delete-company.ts so the two scripts can never drift (a table export
 * claims to cover but delete does not would leave orphaned data after a
 * "complete" deletion; a table delete covers but export does not would mean
 * an export manifest under-represents what a customer's data actually is).
 * src/tests/data-lifecycle.test.ts asserts both scripts import this exact
 * list rather than each keeping their own.
 *
 * Generated by enumerating every `Tables` entry in src/data/db-types.ts
 * (itself generated from the live schema - see `npm run` DB type generation
 * in supabase/README.md) whose Row type has a `company_id` column, cross-
 * checked against `grep -rn "company_id.*references public.companies"
 * supabase/migrations/*.sql`: every one of these 34 tables defines
 * `company_id uuid not null references public.companies (id) on delete
 * cascade` directly (not merely transitively through another table) - see
 * that grep's output for the migration/line each one comes from. Two tables
 * that were briefly company-scoped no longer are and are correctly absent
 * here: `vendor_coverage_limits` (dropped entirely in
 * 20260902000800_compliance_requirements.sql) and `signup_invites`/`leads`/
 * `profiles`/`companies`/`platform_admins`/`contact_submissions`/
 * `upload_rate_limit_counters` (never had a company_id column - some are
 * pre-tenancy, some are intentionally global/pre-auth).
 *
 * Because every one of these 34 tables already has `on delete cascade` from
 * `companies`, deleting the `companies` row itself cascades all of them at
 * the database level - delete-company.ts does not need to (and does not)
 * issue 34 separate DELETE statements. This list still matters for BOTH
 * scripts: export-company.ts uses it to know what to read and report row
 * counts for, and delete-company.ts uses it for its dry-run report (the
 * same row-count preview export produces) even though the real deletion is
 * one cascading DELETE against `companies`.
 *
 * `auth.users` is deliberately NOT in this list and is never touched by
 * either script - see delete-company.ts's own docblock for why.
 */

export const COMPANY_SCOPED_TABLES = [
  "audit_log",
  "audit_snapshots",
  "company_feature_flags",
  "company_invitations",
  "company_members",
  "compliance_cases",
  "compliance_deficiencies",
  "compliance_evaluation_runs",
  "compliance_exceptions",
  "compliance_queue_items",
  "compliance_requirements",
  "contacts",
  "document_extractions",
  "document_processing_jobs",
  "email_delivery_events",
  "email_outbox",
  "package_documents",
  "policy_reminder_log",
  "project_requirement_overrides",
  "project_vendor_assignments",
  "projects",
  "requirement_profile_rules",
  "requirement_profiles",
  "submission_packages",
  "suppressed_recipients",
  "tasks",
  "upload_request_checklist_items",
  "vendor_compliance_items",
  "vendor_contacts",
  "vendor_documents",
  "vendor_import_batches",
  "vendor_policies",
  "vendor_upload_requests",
  "vendors",
] as const;

export type CompanyScopedTable = (typeof COMPANY_SCOPED_TABLES)[number];

/** The one private Supabase Storage bucket that holds customer-uploaded files - see supabase/migrations/20260901000400_vendor_upload_requests_and_documents.sql. */
export const VENDOR_DOCUMENTS_BUCKET = "vendor-documents";

/**
 * Every object in the vendor-documents bucket is written under
 * `company/<companyId>/vendor/<vendorId>/documents/<file>` (see that same
 * migration's storage RLS policy comment, which documents the path shape
 * for the same reason). This is the prefix that scopes a recursive
 * list/download/delete to exactly one company's objects.
 */
export function companyStoragePrefix(companyId: string): string {
  return `company/${companyId}`;
}
