/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRequirementProfilesRouteImport } from './routes/dashboard.requirement-profiles'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as VendorUploadTokenRouteImport } from './routes/vendor-upload.$token'
import { Route as ApiHealthLiveRouteImport } from './routes/api.health.live'
import { Route as ApiHealthReadyRouteImport } from './routes/api.health.ready'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardAdminAccessRouteImport } from './routes/dashboard.admin.access'
import { Route as DashboardAdminActivationRouteImport } from './routes/dashboard.admin.activation'
import { Route as DashboardAdminCompaniesRouteImport } from './routes/dashboard.admin.companies'
import { Route as DashboardAdminComplianceRouteImport } from './routes/dashboard.admin.compliance'
import { Route as DashboardAdminLeadsRouteImport } from './routes/dashboard.admin.leads'
import { Route as DashboardAdminOperationsRouteImport } from './routes/dashboard.admin.operations'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardVendorsIndexRouteImport } from './routes/dashboard.vendors.index'
import { Route as DashboardVendorsVendorIdRouteImport } from './routes/dashboard.vendors.$vendorId'
import { Route as DashboardAdminComplianceQueueItemIdRouteImport } from './routes/dashboard.admin.compliance.$queueItemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/dashboard/help',
  path: '/dashboard/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRequirementProfilesRoute =
  DashboardRequirementProfilesRouteImport.update({
    id: '/dashboard/requirement-profiles',
    path: '/dashboard/requirement-profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/dashboard/tasks',
  path: '/dashboard/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorUploadTokenRoute = VendorUploadTokenRouteImport.update({
  id: '/vendor-upload/$token',
  path: '/vendor-upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/dashboard/admin/',
  path: '/dashboard/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAccessRoute = DashboardAdminAccessRouteImport.update({
  id: '/dashboard/admin/access',
  path: '/dashboard/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminActivationRoute =
  DashboardAdminActivationRouteImport.update({
    id: '/dashboard/admin/activation',
    path: '/dashboard/admin/activation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminCompaniesRoute = DashboardAdminCompaniesRouteImport.update({
  id: '/dashboard/admin/companies',
  path: '/dashboard/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminComplianceRoute =
  DashboardAdminComplianceRouteImport.update({
    id: '/dashboard/admin/compliance',
    path: '/dashboard/admin/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminLeadsRoute = DashboardAdminLeadsRouteImport.update({
  id: '/dashboard/admin/leads',
  path: '/dashboard/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminOperationsRoute =
  DashboardAdminOperationsRouteImport.update({
    id: '/dashboard/admin/operations',
    path: '/dashboard/admin/operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/dashboard/projects/',
  path: '/dashboard/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/dashboard/projects/$projectId',
    path: '/dashboard/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardVendorsIndexRoute = DashboardVendorsIndexRouteImport.update({
  id: '/dashboard/vendors/',
  path: '/dashboard/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVendorsVendorIdRoute =
  DashboardVendorsVendorIdRouteImport.update({
    id: '/dashboard/vendors/$vendorId',
    path: '/dashboard/vendors/$vendorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminComplianceQueueItemIdRoute =
  DashboardAdminComplianceQueueItemIdRouteImport.update({
    id: '/$queueItemId',
    path: '/$queueItemId',
    getParentRoute: () => DashboardAdminComplianceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/requirement-profiles': typeof DashboardRequirementProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/vendor-upload/$token': typeof VendorUploadTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/dashboard/admin/access': typeof DashboardAdminAccessRoute
  '/dashboard/admin/activation': typeof DashboardAdminActivationRoute
  '/dashboard/admin/companies': typeof DashboardAdminCompaniesRoute
  '/dashboard/admin/compliance': typeof DashboardAdminComplianceRouteWithChildren
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRoute
  '/dashboard/admin/operations': typeof DashboardAdminOperationsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/vendors/$vendorId': typeof DashboardVendorsVendorIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/vendors/': typeof DashboardVendorsIndexRoute
  '/dashboard/admin/compliance/$queueItemId': typeof DashboardAdminComplianceQueueItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/requirement-profiles': typeof DashboardRequirementProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/vendor-upload/$token': typeof VendorUploadTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/dashboard/admin/access': typeof DashboardAdminAccessRoute
  '/dashboard/admin/activation': typeof DashboardAdminActivationRoute
  '/dashboard/admin/companies': typeof DashboardAdminCompaniesRoute
  '/dashboard/admin/compliance': typeof DashboardAdminComplianceRouteWithChildren
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRoute
  '/dashboard/admin/operations': typeof DashboardAdminOperationsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/vendors/$vendorId': typeof DashboardVendorsVendorIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/vendors': typeof DashboardVendorsIndexRoute
  '/dashboard/admin/compliance/$queueItemId': typeof DashboardAdminComplianceQueueItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/requirement-profiles': typeof DashboardRequirementProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/vendor-upload/$token': typeof VendorUploadTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/dashboard/admin/access': typeof DashboardAdminAccessRoute
  '/dashboard/admin/activation': typeof DashboardAdminActivationRoute
  '/dashboard/admin/companies': typeof DashboardAdminCompaniesRoute
  '/dashboard/admin/compliance': typeof DashboardAdminComplianceRouteWithChildren
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRoute
  '/dashboard/admin/operations': typeof DashboardAdminOperationsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/vendors/$vendorId': typeof DashboardVendorsVendorIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/vendors/': typeof DashboardVendorsIndexRoute
  '/dashboard/admin/compliance/$queueItemId': typeof DashboardAdminComplianceQueueItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/requirement-profiles'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/vendor-upload/$token'
    | '/dashboard/'
    | '/api/health/live'
    | '/api/health/ready'
    | '/dashboard/admin/access'
    | '/dashboard/admin/activation'
    | '/dashboard/admin/companies'
    | '/dashboard/admin/compliance'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/operations'
    | '/dashboard/projects/$projectId'
    | '/dashboard/vendors/$vendorId'
    | '/dashboard/admin/'
    | '/dashboard/projects/'
    | '/dashboard/vendors/'
    | '/dashboard/admin/compliance/$queueItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/requirement-profiles'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/vendor-upload/$token'
    | '/dashboard'
    | '/api/health/live'
    | '/api/health/ready'
    | '/dashboard/admin/access'
    | '/dashboard/admin/activation'
    | '/dashboard/admin/companies'
    | '/dashboard/admin/compliance'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/operations'
    | '/dashboard/projects/$projectId'
    | '/dashboard/vendors/$vendorId'
    | '/dashboard/admin'
    | '/dashboard/projects'
    | '/dashboard/vendors'
    | '/dashboard/admin/compliance/$queueItemId'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/requirement-profiles'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/vendor-upload/$token'
    | '/dashboard/'
    | '/api/health/live'
    | '/api/health/ready'
    | '/dashboard/admin/access'
    | '/dashboard/admin/activation'
    | '/dashboard/admin/companies'
    | '/dashboard/admin/compliance'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/operations'
    | '/dashboard/projects/$projectId'
    | '/dashboard/vendors/$vendorId'
    | '/dashboard/admin/'
    | '/dashboard/projects/'
    | '/dashboard/vendors/'
    | '/dashboard/admin/compliance/$queueItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRequirementProfilesRoute: typeof DashboardRequirementProfilesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  VendorUploadTokenRoute: typeof VendorUploadTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  DashboardAdminAccessRoute: typeof DashboardAdminAccessRoute
  DashboardAdminActivationRoute: typeof DashboardAdminActivationRoute
  DashboardAdminCompaniesRoute: typeof DashboardAdminCompaniesRoute
  DashboardAdminComplianceRoute: typeof DashboardAdminComplianceRouteWithChildren
  DashboardAdminLeadsRoute: typeof DashboardAdminLeadsRoute
  DashboardAdminOperationsRoute: typeof DashboardAdminOperationsRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardVendorsVendorIdRoute: typeof DashboardVendorsVendorIdRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardVendorsIndexRoute: typeof DashboardVendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/dashboard/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/requirement-profiles': {
      id: '/dashboard/requirement-profiles'
      path: '/dashboard/requirement-profiles'
      fullPath: '/dashboard/requirement-profiles'
      preLoaderRoute: typeof DashboardRequirementProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/dashboard/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-upload/$token': {
      id: '/vendor-upload/$token'
      path: '/vendor-upload/$token'
      fullPath: '/vendor-upload/$token'
      preLoaderRoute: typeof VendorUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/access': {
      id: '/dashboard/admin/access'
      path: '/dashboard/admin/access'
      fullPath: '/dashboard/admin/access'
      preLoaderRoute: typeof DashboardAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/activation': {
      id: '/dashboard/admin/activation'
      path: '/dashboard/admin/activation'
      fullPath: '/dashboard/admin/activation'
      preLoaderRoute: typeof DashboardAdminActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/companies': {
      id: '/dashboard/admin/companies'
      path: '/dashboard/admin/companies'
      fullPath: '/dashboard/admin/companies'
      preLoaderRoute: typeof DashboardAdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/compliance': {
      id: '/dashboard/admin/compliance'
      path: '/dashboard/admin/compliance'
      fullPath: '/dashboard/admin/compliance'
      preLoaderRoute: typeof DashboardAdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/leads': {
      id: '/dashboard/admin/leads'
      path: '/dashboard/admin/leads'
      fullPath: '/dashboard/admin/leads'
      preLoaderRoute: typeof DashboardAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/operations': {
      id: '/dashboard/admin/operations'
      path: '/dashboard/admin/operations'
      fullPath: '/dashboard/admin/operations'
      preLoaderRoute: typeof DashboardAdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/dashboard/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vendors/': {
      id: '/dashboard/vendors/'
      path: '/dashboard/vendors'
      fullPath: '/dashboard/vendors/'
      preLoaderRoute: typeof DashboardVendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vendors/$vendorId': {
      id: '/dashboard/vendors/$vendorId'
      path: '/dashboard/vendors/$vendorId'
      fullPath: '/dashboard/vendors/$vendorId'
      preLoaderRoute: typeof DashboardVendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/compliance/$queueItemId': {
      id: '/dashboard/admin/compliance/$queueItemId'
      path: '/$queueItemId'
      fullPath: '/dashboard/admin/compliance/$queueItemId'
      preLoaderRoute: typeof DashboardAdminComplianceQueueItemIdRouteImport
      parentRoute: typeof DashboardAdminComplianceRoute
    }
  }
}

interface DashboardAdminComplianceRouteChildren {
  DashboardAdminComplianceQueueItemIdRoute: typeof DashboardAdminComplianceQueueItemIdRoute
}

const DashboardAdminComplianceRouteChildren: DashboardAdminComplianceRouteChildren =
  {
    DashboardAdminComplianceQueueItemIdRoute:
      DashboardAdminComplianceQueueItemIdRoute,
  }

const DashboardAdminComplianceRouteWithChildren =
  DashboardAdminComplianceRoute._addFileChildren(
    DashboardAdminComplianceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRequirementProfilesRoute: DashboardRequirementProfilesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  VendorUploadTokenRoute: VendorUploadTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  DashboardAdminAccessRoute: DashboardAdminAccessRoute,
  DashboardAdminActivationRoute: DashboardAdminActivationRoute,
  DashboardAdminCompaniesRoute: DashboardAdminCompaniesRoute,
  DashboardAdminComplianceRoute: DashboardAdminComplianceRouteWithChildren,
  DashboardAdminLeadsRoute: DashboardAdminLeadsRoute,
  DashboardAdminOperationsRoute: DashboardAdminOperationsRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardVendorsVendorIdRoute: DashboardVendorsVendorIdRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardVendorsIndexRoute: DashboardVendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
