-- Phase 1 / migration 4 - the outbound vendor request system, document storage,
-- and the closing half of the loop: vendor -> email -> magic link -> upload.
--
-- Security model for this migration specifically:
--
--   vendor_upload_requests has NO anon or public read/write policy, on purpose.
--   The vendor opening a magic link has no Supabase session - there is no
--   auth.uid() to write a policy against. Resolving a token instead goes through
--   the resolveUploadToken() / uploadDocumentForToken() server functions
--   (src/workflows/vendorUploadRequests.ts), which use the service-role key
--   to bypass RLS *after* independently verifying the hashed token, its expiry,
--   and its status. RLS on this table protects the request metadata from other
--   *tenants*; it deliberately does not gate the anonymous portal, because it
--   cannot - that job belongs to the token check.
--
--   token_hash stores SHA-256 of the token, never the token itself. A dump of
--   this table does not hand out working upload links.

create table public.vendor_upload_requests (
  id             uuid primary key default gen_random_uuid(),
  company_id     uuid not null references public.companies (id) on delete cascade,
  vendor_id      uuid not null references public.vendors (id) on delete cascade,
  token_hash     text not null unique,
  purpose        text not null default 'renewal' check (purpose in ('renewal', 'initial', 'correction')),
  status         text not null default 'pending' check (status in (
                   'pending', 'email_sent', 'opened', 'uploaded', 'processing',
                   'completed', 'needs_review', 'expired', 'cancelled'
                 )),
  expires_at     timestamptz not null,
  opened_at      timestamptz,
  uploaded_at    timestamptz,
  completed_at   timestamptz,
  created_by     uuid references auth.users (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index vendor_upload_requests_vendor_idx on public.vendor_upload_requests (vendor_id);
create index vendor_upload_requests_company_idx on public.vendor_upload_requests (company_id);
-- Powers the "which requests still need a nudge" queries Phase 3 reminders will run.
create index vendor_upload_requests_open_idx on public.vendor_upload_requests (expires_at)
  where status not in ('completed', 'expired', 'cancelled');

create trigger vendor_upload_requests_touch_updated_at
  before update on public.vendor_upload_requests
  for each row execute function public.touch_updated_at();

-- vendor_id is not null here, so the existing generic trigger applies unchanged.
create trigger vendor_upload_requests_company_matches_vendor
  before insert or update on public.vendor_upload_requests
  for each row execute function public.assert_company_matches_vendor();

alter table public.vendor_upload_requests enable row level security;

-- Company members can see and create requests for their own vendors, same as
-- every other company-scoped table. There is intentionally no anon policy.
create policy vendor_upload_requests_select on public.vendor_upload_requests
  for select to authenticated
  using (company_id in (select public.current_company_ids()) or public.is_platform_admin());

create policy vendor_upload_requests_insert on public.vendor_upload_requests
  for insert to authenticated
  with check (public.can_write_company(company_id));

create policy vendor_upload_requests_update on public.vendor_upload_requests
  for update to authenticated
  using (public.can_write_company(company_id))
  with check (public.can_write_company(company_id));

-- No delete policy: a request is evidence of what was asked and when: it should
-- expire or be cancelled, not disappear from the audit trail.

-- ---------------------------------------------------------------------------
-- vendor_documents
-- ---------------------------------------------------------------------------

create table public.vendor_documents (
  id                 uuid primary key default gen_random_uuid(),
  company_id         uuid not null references public.companies (id) on delete cascade,
  vendor_id          uuid not null references public.vendors (id) on delete cascade,
  upload_request_id  uuid references public.vendor_upload_requests (id) on delete set null,
  -- Server-generated by buildStoragePath(); never derived from a client-supplied
  -- name. See src/workflows/uploadTokens.ts.
  storage_path       text not null unique,
  file_name          text not null,
  mime_type          text not null,
  file_size          bigint not null check (file_size > 0 and file_size <= 26214400),
  sha256             text not null,
  source             text not null default 'vendor_portal'
                       check (source in ('vendor_portal', 'client_upload', 'admin', 'email')),
  -- Phase 2 (OCR/extraction) will drive this past 'uploaded'. Uploading a file
  -- never implies compliance - see vendor_compliance_items, which this table
  -- does not touch.
  processing_status  text not null default 'uploaded'
                       check (processing_status in ('uploaded', 'processing', 'processed', 'needs_review', 'failed')),
  processing_error   text,
  uploaded_at        timestamptz not null default now(),
  processed_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index vendor_documents_vendor_idx on public.vendor_documents (vendor_id);
create index vendor_documents_company_idx on public.vendor_documents (company_id);
create index vendor_documents_upload_request_idx on public.vendor_documents (upload_request_id);
-- Duplicate-upload detection, scoped per vendor rather than globally: the same
-- COI legitimately gets re-uploaded for different vendors (a broker's template).
create index vendor_documents_sha256_idx on public.vendor_documents (vendor_id, sha256);

create trigger vendor_documents_touch_updated_at
  before update on public.vendor_documents
  for each row execute function public.touch_updated_at();

create trigger vendor_documents_company_matches_vendor
  before insert or update on public.vendor_documents
  for each row execute function public.assert_company_matches_vendor();

alter table public.vendor_documents enable row level security;

create policy vendor_documents_select on public.vendor_documents
  for select to authenticated
  using (company_id in (select public.current_company_ids()) or public.is_platform_admin());

create policy vendor_documents_insert on public.vendor_documents
  for insert to authenticated
  with check (public.can_write_company(company_id));

create policy vendor_documents_update on public.vendor_documents
  for update to authenticated
  using (public.can_write_company(company_id))
  with check (public.can_write_company(company_id));

-- No delete policy: same reasoning as vendor_upload_requests - a received
-- document is part of the compliance record, not something to quietly remove.

-- ---------------------------------------------------------------------------
-- email_outbox
-- ---------------------------------------------------------------------------

-- Simplified from the two-table (email_events / email_deliveries) design a
-- review of this schema recommended. One row per send attempt is enough to
-- answer "did this go out" for Phase 1; split it once delivery-webhook data
-- (opened/clicked/bounced) actually needs its own lifecycle in Phase 3.
create table public.email_outbox (
  id                 uuid primary key default gen_random_uuid(),
  company_id         uuid not null references public.companies (id) on delete cascade,
  vendor_id          uuid not null references public.vendors (id) on delete cascade,
  upload_request_id  uuid references public.vendor_upload_requests (id) on delete set null,
  template           text not null check (template in ('vendor_onboarding', 'renewal_request')),
  to_email           text not null,
  status             text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  provider_message_id text,
  error              text,
  sent_at            timestamptz,
  created_at         timestamptz not null default now()
);

create index email_outbox_vendor_idx on public.email_outbox (vendor_id);
create index email_outbox_company_idx on public.email_outbox (company_id);

create trigger email_outbox_company_matches_vendor
  before insert or update on public.email_outbox
  for each row execute function public.assert_company_matches_vendor();

alter table public.email_outbox enable row level security;

create policy email_outbox_select on public.email_outbox
  for select to authenticated
  using (company_id in (select public.current_company_ids()) or public.is_platform_admin());

create policy email_outbox_insert on public.email_outbox
  for insert to authenticated
  with check (public.can_write_company(company_id));

-- No update/delete policy for authenticated users: status transitions
-- (queued -> sent/failed) are written by the server function using the same
-- request-scoped session that created the row, immediately after the send
-- attempt - not edited later by anyone.

-- ---------------------------------------------------------------------------
-- Storage: private bucket for uploaded certificates
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vendor-documents',
  'vendor-documents',
  false,
  26214400, -- 25 MB, matches vendor_documents.file_size and MAX_UPLOAD_BYTES in src/workflows/uploadTokens.ts
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do nothing;

-- Objects are written exclusively through uploadDocumentForToken() using the
-- service-role key (which bypasses storage RLS same as table RLS), because the
-- uploader is an anonymous vendor with no session. This policy therefore only
-- ever needs to grant *read* access, to authenticated company members viewing
-- their own vendor's documents - there is no authenticated write path to allow.
--
-- storage.foldername() splits the object path on '/' and drops the file name,
-- so for "company/<companyId>/vendor/<vendorId>/documents/<id>.pdf" segment
-- [2] is the companyId.
-- The uuid cast on the folder segment is guarded by a regex match first: AND is
-- not guaranteed left-to-right by the planner, so without the guard a future
-- bucket whose paths don't start with a uuid segment could make this policy
-- throw (not just return false) when both policies are evaluated in the same
-- scan of storage.objects.
create policy vendor_documents_bucket_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'vendor-documents'
    and (storage.foldername(name))[1] = 'company'
    and (storage.foldername(name))[2] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    and ((storage.foldername(name))[2])::uuid in (select public.current_company_ids())
  );
